### ISSUE TITLE
Publish Flutter package

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#223]
I think the title speaks for itself.

**Comment by aniketambore** [comment]
The plugin is not published on pub.dev, but I think Flutter developers can directly use the plugin from here itself: https://github.com/breez/breez-sdk-flutter by modifying their pubspec.yaml as follows:

```yaml
dependencies:
  breez_sdk:
    git:
      url: https://github.com/breez/breez-sdk-flutter.git
```
